[Component with its own class name as service type] LPS-193512 Refactor Cache classes from portal-template module
rafaprax/liferay-portal pull request #1272
Opened 2023-09-06 20:31 UTC by MrJohn1911

2023-09-06 20:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-06 20:32 UTC, MrJohn1911 commented
ci:test:sf

2023-09-06 20:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/7268/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7268/jenkins-report.html">here</a>.</b></p>

2023-09-06 20:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/954bb64877eb53b63d7ed5385dca27279761e861">954bb64877eb53b63d7ed5385dca27279761e861</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-193512">LPS-193512</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/b4ccf8e25cb75c257f087df38622f357b3ede72c">b4ccf8e25cb75c257f087df38622f357b3ede72c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7268/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7268/jenkins-report.html">here</a>.</h5></details></html>

2023-09-06 20:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/7268/">test-portal-source-format#7268</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/7268/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1272">rafaprax#1272</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2419833525">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1272 - 2023-09-06[13:32:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/27021/">publish-testray-report#27021</a><br/></div></div>

2023-09-13 01:19 UTC, rafaprax requested changes

2023-09-13 01:19 UTC, rafaprax commented on modules/apps/portal-template/portal-template-freemarker/src/test/java/com/liferay/portal/template/freemarker/internal/FreeMarkerTemplateTest.java
> +		ReflectionTestUtil.setFieldValue(
Hey @MrJohn1911, extract the repeated code to a method and reuse here. Thx

2023-09-13 01:19 UTC, rafaprax commented on modules/apps/portal-template/portal-template-velocity/src/main/java/com/liferay/portal/template/velocity/internal/VelocityManager.java
> +					VelocityManager.VelocityTemplateResourceLoader.class.
for this case we can make the inner class public since it is used in the production code.

2023-09-13 01:19 UTC, rafaprax commented on modules/apps/portal-template/portal-template-velocity/src/main/java/com/liferay/portal/template/velocity/internal/VelocityManager.java
> +		new VelocityTemplateResourceCache();
initialize these fields on the activate method

2023-09-25 15:26 UTC, closed without merging