[Component with its own class name as service type] LPS-196642 Refactor components from commerce, objects and lima modules
rafaprax/liferay-portal pull request #1277
Opened 2023-09-19 19:59 UTC by MrJohn1911

2023-09-19 19:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-09-20 18:19 UTC, rafaprax requested changes

2023-09-20 18:19 UTC, rafaprax commented on modules/apps/commerce/commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/cart/CommerceCartResource.java
> +		public Cart getCart(
just move the methods from CommerceCartResourceUtil to the outer class. No need to have an inner class here.

2023-09-20 18:19 UTC, rafaprax commented on modules/apps/adaptive-media/adaptive-media-image-service/src/main/java/com/liferay/adaptive/media/image/service/impl/AMImageEntryLocalServiceImpl.java
> +	public class ImageStorage {
keep it an isolated class and its dependencies as constructor parameters.

2023-09-20 20:21 UTC, MrJohn1911 commented
ci:test:sf

2023-09-20 20:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4089/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4089/jenkins-report.html">here</a>.</b></p>

2023-09-20 20:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4a34c2b87f4834caa8ba0e8db89147fbc9f0c577">4a34c2b87f4834caa8ba0e8db89147fbc9f0c577</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-196642">LPS-196642</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/bb1d68a974136a792c55ef43c3bd53046022eb5c">bb1d68a974136a792c55ef43c3bd53046022eb5c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4089/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4089/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: Property value 'commons-collections:commons-collections-&gt;modules/apps/portal-template/portal-template-velocity/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 2: Property value 'commons-collections:commons-collections-&gt;modules/dxp/apps/saml/saml-opensaml-integration/build.gradle' points to file that does not exist: /opt/dev/projects/github/liferay-portal/modules/source-formatter.properties (SourceCheck:PropertiesSourceFormatterFileCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:290)
[stopwatch] [run.batch.test.action: 1:04.714 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:504: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:648: Java returned: 1
      [get] Getting: http://test-1-39/job/test-portal-source-format/4089//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20230920132433605.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20230920132433605.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1358261476.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1965583796
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 169ms
[junitreport] Deleting: /tmp/null1965583796
     [echo] A report with all the test results can be found at test-results/html/index.html.</pre></details></html>

2023-09-20 20:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4089/">test-portal-source-format#4089</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4089/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1277">rafaprax#1277</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2428387127">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1277 - 2023-09-20[13:21:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/15207/">publish-testray-report#15207</a><br/></div></div>

2023-09-26 18:53 UTC, rafaprax requested changes

2023-09-26 18:53 UTC, rafaprax commented on modules/apps/commerce/commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/security/resource/permission/CommerceVirtualOrderItemPermissionUtil.java
> +	public static boolean contains(
remove this classe and call the `commerceVirtualOrderItemModelResourcePermission#contains` directly.

2023-09-27 13:22 UTC, closed without merging