LPS-199148 Transform ResourceBundleLoaderProvider to class util, and apply to usages
rafaprax/liferay-portal pull request #1301
Opened 2023-10-17 19:24 UTC by Valmir-unicap

2023-10-17 19:24 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-17 19:25 UTC, Valmir-unicap commented
ci:test:sf

2023-10-17 19:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</b></p>

2023-10-17 19:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1c5dca33fc65a5f5518c04cafacf7045f4f7d4a0">1c5dca33fc65a5f5518c04cafacf7045f4f7d4a0</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199148">LPS-199148</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/4d543a7dfebac48214132e3d76cf06bf62c58035">4d543a7dfebac48214132e3d76cf06bf62c58035</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">here</a>.</h5></details></html>

2023-10-17 19:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/4952/">test-portal-source-format#4952</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/4952/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1301">rafaprax#1301</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2442514551">[master] ci:test:sf - Valmir-unicap &gt; rafaprax - PR#1301 - 2023-10-17[12:25:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/18794/">publish-testray-report#18794</a><br/></div></div>

2023-10-25 13:48 UTC, rafaprax requested changes

2023-10-25 13:48 UTC, rafaprax commented on modules/apps/configuration-admin/configuration-admin-web/src/main/java/com/liferay/configuration/admin/web/internal/util/ResourceBundleLoaderProviderUtil.java
> +	private static final ServiceTrackerMap<String, ResourceBundleLoader>
Hey @Valmir-unicap, you do not need this tracker. Use the `ResourceBundleLoaderUtil` instead. Thx

2023-10-25 13:48 UTC, rafaprax commented on modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/template/TemplateHandlerRegistryImpl.java
> +	private ServiceTrackerMap<String, ResourceBundleLoader> _serviceTrackerMap;
Hey @Valmir-unicap, you do not need this tracker. Use the `ResourceBundleLoaderUtil` instead. Thx

2023-10-25 13:48 UTC, closed without merging

2023-11-09 18:14 UTC, Valmir-unicap commented
Fix finish!!! Sent to team repository.
Pr: https://github.com/liferay-core-infra/liferay-portal/pull/5928