LPS-199599 Inline SpeedwellLayoutsInitializer methods into SpeedwellSiteInitializer
rafaprax/liferay-portal pull request #1307
Opened 2023-10-20 19:59 UTC by MrJohn1911

2023-10-20 19:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-10-20 20:12 UTC, MrJohn1911 commented
ci:test:sf

2023-10-20 20:59 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/5895/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5895/jenkins-report.html">here</a>.</b></p>

2023-10-20 21:01 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 48 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a58682d046eb2821b21d550c683c4351863af365">a58682d046eb2821b21d550c683c4351863af365</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/rand-169783194831456">rand-169783194831456</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/5cec5ec4213f02494eea3aa6638cfbb90857b00e">5cec5ec4213f02494eea3aa6638cfbb90857b00e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5895/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5895/jenkins-report.html">here</a>.</h5></details></html>

2023-10-20 21:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/5895/">test-portal-source-format#5895</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/5895/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1307">rafaprax#1307</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2444600653">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1307 - 2023-10-20[13:13:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/22459/">publish-testray-report#22459</a><br/></div></div>

2023-10-26 14:37 UTC, rafaprax requested changes
Hey @MrJohn1911, just apply the changes we discussed yesterday related to your first and second commits. Thx

2023-10-26 14:39 UTC, closed without merging