[Component with its own class name as service type ] LPS-199464 Refactor Helper class from document-library and portal
rafaprax/liferay-portal pull request #1309
Opened 2023-10-23 15:54 UTC by GabrielHenriquedev

2023-10-23 16:00 UTC, GabrielHenriquedev commented
ci:test:sf

2023-10-23 16:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8493/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8493/jenkins-report.html">here</a>.</b></p>

2023-10-23 16:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ec9659f8692eda97cc3dc9bdf770ae28cbf2f81c">ec9659f8692eda97cc3dc9bdf770ae28cbf2f81c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/GabrielHenriquedev/liferay-portal/tree/LPS-199464">LPS-199464</a><br/>Branch GIT ID: <a href="https://github.com/GabrielHenriquedev/liferay-portal/commit/234d8e679d85b37a6773af6aca80dca537f0b88b">234d8e679d85b37a6773af6aca80dca537f0b88b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8493/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8493/jenkins-report.html">here</a>.</h5></details></html>

2023-10-23 16:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8493/">test-portal-source-format#8493</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8493/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1309">rafaprax#1309</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2445460533">[master] ci:test:sf - GabrielHenriquedev &gt; rafaprax - PR#1309 - 2023-10-23[09:01:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/32278/">publish-testray-report#32278</a><br/></div></div>

2023-10-27 13:00 UTC, rafaprax requested changes
Hey @GabrielHenriquedev, the changes are good but the commit message of the 2nd commit is wrong. Please fix the commit message and send the changes to the core repo

2023-10-27 13:00 UTC, closed without merging