[Component with its own class name as service type ] LPS-199482 Refactor classes JAXRSLifecycle and KaleoTaskScriptedAssignmentCache
rafaprax/liferay-portal pull request #1372
Opened 2023-12-05 22:05 UTC by Valmir-unicap

2023-12-05 22:05 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-07 20:34 UTC, rafaprax requested changes

2023-12-07 20:48 UTC, Valmir-unicap commented on modules/apps/portal-remote/portal-remote-jaxrs-whiteboard/src/main/java/com/liferay/portal/remote/jaxrs/whiteboard/lifecycle/JAXRSLifecycle.java
> -		if (_jaxrsReady) {
I did what you suggested: 

- @RenanUmV, first remove the _jaxrsReady variable and then transform it to a Util class. Also, verify a solution for the _serviceRegistrationDCLSingleton.destroy call as well.

2023-12-11 13:41 UTC, rafaprax commented on modules/apps/portal-remote/portal-remote-jaxrs-whiteboard/src/main/java/com/liferay/portal/remote/jaxrs/whiteboard/lifecycle/JAXRSLifecycle.java
> -		if (_jaxrsReady) {
I know but you need to explain it in the commit message. I'm just the first reviewer in the chain and your current commit message doesn't explain the reason why you did that.

2023-12-11 13:42 UTC, rafaprax commented on modules/apps/portal-remote/portal-remote-jaxrs-whiteboard/src/main/java/com/liferay/portal/remote/jaxrs/whiteboard/lifecycle/JAXRSLifecycle.java
> -		if (_jaxrsReady) {
Makes sense?

2023-12-11 21:32 UTC, Valmir-unicap commented
ci:test:sf

2023-12-11 21:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5436/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5436/jenkins-report.html">here</a>.</b></p>

2023-12-11 21:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839d8c833229e39af7aca40aae16059f4be25bee">839d8c833229e39af7aca40aae16059f4be25bee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199482-Conclued">LPS-199482-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/2f9a849d729f165744dab6143edae65842bd8d81">2f9a849d729f165744dab6143edae65842bd8d81</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5436/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5436/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 21:54 UTC, Valmir-unicap commented
ci:test:sf

2023-12-11 21:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/3020/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3020/jenkins-report.html">here</a>.</b></p>

2023-12-11 21:57 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/839d8c833229e39af7aca40aae16059f4be25bee">839d8c833229e39af7aca40aae16059f4be25bee</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199482-Conclued">LPS-199482-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/c80c2e2d4ecdc181a304d45f36e3f3b8769cee32">c80c2e2d4ecdc181a304d45f36e3f3b8769cee32</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3020/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3020/jenkins-report.html">here</a>.</h5></details></html>

2023-12-11 21:59 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/3020/">test-portal-source-format#3020</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/3020/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1372">rafaprax#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2473035440">[master] ci:test:sf - Valmir-unicap &gt; rafaprax - PR#1372 - 2023-12-11[13:54:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/22191/">publish-testray-report#22191</a><br/></div></div>

2023-12-14 13:52 UTC, rafaprax requested changes

2023-12-14 13:52 UTC, rafaprax commented on modules/apps/portal-remote/portal-remote-jaxrs-whiteboard/src/main/java/com/liferay/portal/remote/jaxrs/whiteboard/util/JAXRSLifecycleUtil.java
> +	public static void ensureUnReady() {
@Valmir-unicap rename to `ensureUnready`

2023-12-14 20:08 UTC, rafaprax requested changes

2023-12-14 20:08 UTC, rafaprax commented on modules/apps/oauth2-provider/oauth2-provider-scope-impl/src/main/java/com/liferay/oauth2/provider/scope/internal/liferay/ScopeLocatorImpl.java
> +		JAXRSLifecycleUtil.ensureReady();
Hey @Valmir-unicap, please add a breaking change note for this commit. I didn't see this before 😞

2023-12-14 21:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5287/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5287/jenkins-report.html">here</a>.</b></p>

2023-12-14 21:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6af76e46fccdeab086dc5da2bd0f08cbddbfa39a">6af76e46fccdeab086dc5da2bd0f08cbddbfa39a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199482-Conclued">LPS-199482-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/2e0959d3f3888acac663355326fa72ded861673a">2e0959d3f3888acac663355326fa72ded861673a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5287/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5287/jenkins-report.html">here</a>.</h5></details></html>

2023-12-14 21:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5287/">test-portal-source-format#5287</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5287/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1372">rafaprax#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474730228">[master] ci:test:sf - Valmir-unicap &gt; rafaprax - PR#1372 - 2023-12-14[13:28:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/20380/">publish-testray-report#20380</a><br/></div></div>

2023-12-18 12:56 UTC, rafaprax requested changes
@Valmir-unicap the breaking change you made wasn't in the `bnd.bnd` file. This `bnd.bnd`'s change is a result of the breaking change. https://github.com/rafaprax/liferay-portal/pull/1372/commits/379cd814489393e971b13773f3c4abf48d4654c0

Please fix the commit message to reflect that and pay attention to the details. Ask @MrJohn1911 help and review for that.

Thx

2023-12-18 21:58 UTC, Valmir-unicap commented
ci:test:sf

2023-12-18 22:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/5110/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">here</a>.</b></p>

2023-12-18 22:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/73b8b030ce7a7936ab9d51f0ad68832a30f49c19">73b8b030ce7a7936ab9d51f0ad68832a30f49c19</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199482-Conclued">LPS-199482-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/1ab941a79a832e8ada5869c55849f0556999a3ed">1ab941a79a832e8ada5869c55849f0556999a3ed</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5110/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">here</a>.</h5></details></html>

2023-12-18 22:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/5110/">test-portal-source-format#5110</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/5110/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1372">rafaprax#1372</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2476168556">[master] ci:test:sf - Valmir-unicap &gt; rafaprax - PR#1372 - 2023-12-18[13:58:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/19849/">publish-testray-report#19849</a><br/></div></div>

2023-12-22 17:21 UTC, rafaprax approved these changes

2023-12-22 17:22 UTC, rafaprax commented
forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/6363

2023-12-22 17:22 UTC, closed without merging