[Components with more than 1 service] LPS-192202 Refactor export-import components
rafaprax/liferay-portal pull request #1374
Opened 2023-12-06 19:15 UTC by MrJohn1911

2023-12-06 19:15 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-06 19:16 UTC, MrJohn1911 commented
ci:test:sf

2023-12-06 19:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/3977/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3977/jenkins-report.html">here</a>.</b></p>

2023-12-06 19:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/617eb3201c2ad33025bfe6a3989ba90c268431ba">617eb3201c2ad33025bfe6a3989ba90c268431ba</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-192202">LPS-192202</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/e1250fa3c854e80f8fbe01a6114a520c312cd0af">e1250fa3c854e80f8fbe01a6114a520c312cd0af</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3977/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3977/jenkins-report.html">here</a>.</h5></details></html>

2023-12-06 19:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/3977/">test-portal-source-format#3977</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/3977/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1374">rafaprax#1374</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2471526057">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1374 - 2023-12-06[11:17:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/15263/">publish-testray-report#15263</a><br/></div></div>

2023-12-11 14:33 UTC, rafaprax requested changes
Hey @MrJohn1911, why we need to add a breaking change note in the first commit?

2023-12-14 15:12 UTC, rafaprax requested changes

2023-12-14 16:31 UTC, rafaprax commented
Hey @MrJohn1911, about this https://github.com/rafaprax/liferay-portal/pull/1374/commits/d4e829736e17b8e5a38d15c8b6372ed921424cfd and this https://github.com/rafaprax/liferay-portal/pull/1374/commits/68f608bac563e5908dcb3dc406e896cf3615c3ef. It would be better if we:

1. Inline the  `ExportImportControllerRegistryUtil` into the `ExportImportManager`;
2. Replace the ServiceTracker usages by single `@Reference` references
3. Remove the unused interfaces

Thanks

2023-12-14 17:16 UTC, rafaprax requested changes

2023-12-14 17:16 UTC, rafaprax commented on portal-impl/src/com/liferay/portlet/exportimport/service/impl/ExportImportLocalServiceImpl.java
> -
Hey @MrJohn1911, update the commit message to say that you moved the Service and ServiceImpl to the Manager class. Thx

2023-12-14 20:17 UTC, MrJohn1911 commented
ci:test:sf

2023-12-14 20:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/2306/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2306/jenkins-report.html">here</a>.</b></p>

2023-12-14 20:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6af76e46fccdeab086dc5da2bd0f08cbddbfa39a">6af76e46fccdeab086dc5da2bd0f08cbddbfa39a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-192202">LPS-192202</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/1028f020a3ac3de09f7d1aac859c4b78317002fb">1028f020a3ac3de09f7d1aac859c4b78317002fb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2306/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2306/jenkins-report.html">here</a>.</h5></details></html>

2023-12-14 20:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2306/">test-portal-source-format#2306</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2306/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1374">rafaprax#1374</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2474727356">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1374 - 2023-12-14[12:17:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9059/">publish-testray-report#9059</a><br/></div></div>

2023-12-15 20:16 UTC, rafaprax approved these changes

2023-12-15 20:17 UTC, rafaprax commented
forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/6331

2023-12-15 20:17 UTC, closed without merging