[Component with its own class name as service type] LPS-199657 Refactor Registry classes from object and content-dashboard module
rafaprax/liferay-portal pull request #1381
Opened 2023-12-20 20:20 UTC by Valmir-unicap

2023-12-20 20:20 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-20 20:23 UTC, Valmir-unicap commented
ci:test:sf

2023-12-20 20:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0489079f5e888f871139f9089fc27c2ef56c9dc5">0489079f5e888f871139f9089fc27c2ef56c9dc5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-199657-Conclued">LPS-199657-Conclued</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/f1c5c7971b77a7273b84522ee7687c09a39a8162">f1c5c7971b77a7273b84522ee7687c09a39a8162</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2591/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2591/jenkins-report.html">here</a>.</h5></details></html>

2023-12-28 21:05 UTC, MrJohn1911 approved these changes

2024-01-04 19:56 UTC, rafaprax requested changes

2024-01-04 19:56 UTC, rafaprax commented on modules/apps/content-dashboard/content-dashboard-web/src/main/java/com/liferay/content/dashboard/web/internal/display/context/ContentDashboardAdminManagementToolbarDisplayContext.java
> +		ServiceTrackerList<ContentDashboardItemFilterProvider>
sort paramaters

2024-01-04 19:56 UTC, rafaprax commented on modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/display/context/ContentDashboardAdminManagementToolbarDisplayContextTest.java
> +		ServiceTrackerList<ContentDashboardItemFilterProvider>
rename to `contentDashboardItemFilterProviderServiceTrackerList`

2024-01-04 19:56 UTC, rafaprax commented on modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/display/context/ContentDashboardAdminManagementToolbarDisplayContextTest.java
> +	private class ContentDashboardItemFilterProviderImpl
rename to `MockContentDashboardItemFilterProvider `

2024-01-04 19:56 UTC, closed without merging