[Component with its own class name as service type] LPS-200419 Refactor Adapter component
rafaprax/liferay-portal pull request #1384
Opened 2023-12-22 21:31 UTC by Valmir-unicap

2023-12-22 21:31 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-12-22 21:35 UTC, Valmir-unicap commented
ci:test:sf

2023-12-22 21:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/2607/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2607/jenkins-report.html">here</a>.</b></p>

2023-12-22 21:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dafc5f0b890c91811c016c1737867e0b258550c9">dafc5f0b890c91811c016c1737867e0b258550c9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Valmir-unicap/liferay-portal/tree/LPS-200419">LPS-200419</a><br/>Branch GIT ID: <a href="https://github.com/Valmir-unicap/liferay-portal/commit/56acedd116be8079b8f498ae94088ee2c820cd2d">56acedd116be8079b8f498ae94088ee2c820cd2d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2607/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2607/jenkins-report.html">here</a>.</h5></details></html>

2023-12-22 21:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/2607/">test-portal-source-format#2607</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/2607/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1384">rafaprax#1384</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2478728770">[master] ci:test:sf - Valmir-unicap &gt; rafaprax - PR#1384 - 2023-12-22[13:35:55]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2478728770<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/11061/">publish-testray-report#11061</a><br/></div></div>

2023-12-28 20:52 UTC, MrJohn1911 approved these changes

2023-12-28 21:15 UTC, Valmir-unicap commented
I pushed just to adjust the name of the submission suggested by @MrJohn1911

2024-01-04 20:06 UTC, rafaprax requested changes

2024-01-04 20:06 UTC, rafaprax commented on modules/dxp/apps/portal-search-tuning/portal-search-tuning-synonyms-web/src/main/java/com/liferay/portal/search/tuning/synonyms/web/internal/storage/SynonymSetStorageAdapter.java
> +
make the singleton thread safe or transform it into a Util class

2024-01-04 20:06 UTC, rafaprax commented
and fix conflicts

2024-01-04 20:06 UTC, closed without merging