[Components with more than 1 service] LPS-206064 Refactor OAuth2AuthorizationExpandoPortalInstanceLifecycleListener component
rafaprax/liferay-portal pull request #1402
Opened 2024-01-11 20:08 UTC by MrJohn1911

2024-01-11 20:08 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-01-11 20:09 UTC, MrJohn1911 commented
ci:test:sf

2024-01-11 20:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7415/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7415/jenkins-report.html">here</a>.</b></p>

2024-01-11 20:14 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fff775e599f3515c078fb8c504e13a15b7fabb99">fff775e599f3515c078fb8c504e13a15b7fabb99</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-206064">LPS-206064</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/6a2fbfc80c9305024d98574391f2d0c0d5aebd1d">6a2fbfc80c9305024d98574391f2d0c0d5aebd1d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7415/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7415/jenkins-report.html">here</a>.</h5></details></html>

2024-01-12 16:35 UTC, rafaprax requested changes

2024-01-12 16:35 UTC, rafaprax commented on modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/java/com/liferay/osb/faro/web/internal/constants/SAPEntryObjectConstants.java
> +public class SAPEntryObjectConstants {
rename to `FaroSAPConstants`

2024-01-12 16:48 UTC, MrJohn1911 commented
ci:test:sf

2024-01-12 16:50 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/8095/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8095/jenkins-report.html">here</a>.</b></p>

2024-01-12 16:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fff775e599f3515c078fb8c504e13a15b7fabb99">fff775e599f3515c078fb8c504e13a15b7fabb99</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/MrJohn1911/liferay-portal/tree/LPS-206064">LPS-206064</a><br/>Branch GIT ID: <a href="https://github.com/MrJohn1911/liferay-portal/commit/b99493fcc875d6e237198d0ddfd2e4aa7e5f98e5">b99493fcc875d6e237198d0ddfd2e4aa7e5f98e5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8095/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8095/jenkins-report.html">here</a>.</h5></details></html>

2024-01-12 16:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/8095/">test-portal-source-format#8095</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/8095/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1402">rafaprax#1402</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2487502638">[master] ci:test:sf - MrJohn1911 &gt; rafaprax - PR#1402 - 2024-01-12[08:49:13]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2487502638<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/30222/">publish-testray-report#30222</a><br/></div></div>

2024-01-12 19:05 UTC, rafaprax commented
forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/6459

2024-01-12 19:07 UTC, rafaprax approved these changes

2024-01-12 19:07 UTC, closed without merging