LPD-1948 Use of library with known vulnerability: Apache Freemarker 2.3.29
rafaprax/liferay-portal pull request #1419
Opened 2024-01-29 21:25 UTC by RenanUmV

2024-01-29 21:25 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-01-29 21:25 UTC, RenanUmV commented
ci:test:sf

2024-01-29 21:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/8864/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8864/jenkins-report.html">here</a>.</b></p>

2024-01-29 21:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 23 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5e8b7d8851d17b95846e31290ef0336ac92dca0c">5e8b7d8851d17b95846e31290ef0336ac92dca0c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/RenanUmV/liferay-portal/tree/LPD-1948">LPD-1948</a><br/>Branch GIT ID: <a href="https://github.com/RenanUmV/liferay-portal/commit/cb5d7ebacc88e7a52f8ccfab7eb182ae3b43bc64">cb5d7ebacc88e7a52f8ccfab7eb182ae3b43bc64</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8864/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8864/jenkins-report.html">here</a>.</h5></details></html>

2024-01-29 21:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/8864/">test-portal-source-format#8864</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/8864/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rafaprax/liferay-portal/pull/1419">rafaprax#1419</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2532311154">[master] ci:test:sf - RenanUmV &gt; rafaprax - PR#1419 - 2024-01-29[13:26:27]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2532311154<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/34049/">publish-testray-report#34049</a><br/></div></div>

2024-01-30 20:32 UTC, rafaprax requested changes

2024-01-30 20:32 UTC, rafaprax commented on lib/versions-ext.xml
> +				<version>2.3.30.LIFERAY-PATCHED-1</version>
It should be in the "ant build-lib-versions" commit

2024-01-30 20:32 UTC, rafaprax commented on modules/apps/document-library-google-docs/document-library-google-docs/build.gradle
> -	compileInclude group: "com.liferay", name: "org.freemarker", version: "2.3.29.LIFERAY-PATCHED-5"
this commit should come after this https://github.com/rafaprax/liferay-portal/pull/1419/commits/5c0d804b8af46fb8b3cadf615b7ec22168cdf293#diff-8eecd0fb1ae096fcfd2a3868810c20ada706bb28f33c280a049445a13fc47a2fR28 change and the message should be something like "Auto SF"

2024-01-31 12:49 UTC, closed without merging